### ISSUE TITLE
Gold is not shared upon purchase.

### ISSUE THREAD

**Issue by TaironBrunelli** [Frenqy/InstancedLoot_continuation#2]
In the previous mod, the gold was always the same, and both players lost gold when they bought something.
In the current mod, only the gold of the player who bought something is reduced.

**Comment by KubeRoot** [comment]
I don't think that was ever the case - that sounds like a ShareSuite feature, did you perhaps use them together or confuse the mods?

**Comment by Frenqy** [comment]
> only the gold of the player who bought something is reduced.

This is the behavior of the original game, so I think it work as intended

**Comment by 6d657263757279** [comment]
I wouldn't want both players to lose gold when only one player makes a purchase, not by default anyway. Perhaps this could be a useful config setting if players are using the InstanceItems config. In that case, it might be better to use ShareSuite if your goal is to have all items be duplicated and shared for both players. In my case, I do not want this and prefer that each player open their own objects and can only take their own items (except for duplicators/etc).

**Comment by TaironBrunelli** [comment]
Forgive me, I forgot to add this little and very important part where I was using the "InstanceItems" config.
Where one chest will drop 2 items (if there are 2 players in the session). In this case would be better if the gold for both players was reduced from any buy.

**Comment by KubeRoot** [comment]
That is fair, but again, I don't believe InstancedLoot ever had such a feature. It does have a configurable option to reduce money drops, making it so each player only receives half the money they would usually get, with the same effective balance implications.

I'd say it's fair to request such a feature, but if you want to pivot in that direction, I would recommend you rename the issue to reflect that.

**Comment by TaironBrunelli** [comment]
No KubeRoot, I posted it as an error because I believe that was a feature in the previous mod.
I never used the ShareSuite, but I played with the InstanceItems option, which had this—at least my friend and I remember "sharing the gold."
But, if it was a bug/feature because others mod, I don't know.

**Comment by KubeRoot** [comment]
I don't want to drag this out, and I feel like it's already getting drawn out and confusing...

I want to reiterate one thing: I made InstancedLoot from scratch, you can see my commits in the repository (since it was forked), and I am pretty damn sure I never implemented such a thing. I went back to check the source on the original repository, just to be sure, and couldn't find a mention of that. As far as I remember, the mod never kept track of how much gold purchasing an interactible cost - the cost is only touched one, when instancing interactibles, to copy it to the instanced copies, and never interacted with again.

It's based on this knowledge of the source that I'm saying, I'm pretty sure it's not a bug and was never a bug - InstancedLoot never modified players' money when another player purchased something.

One thing to note is, if I'm not mistaken, ShareSuite is a serverside mod - this means that if the player hosting it had it installed and setup, it would affect everybody playing without them needing to install that too. Depending on how you played, maybe the host set it up separately at some point, and you forgot about it?

This is also why I recommend rephrasing the issue as a feature request - AFAIK it was never a thing, thus it couldn't be a bug. Ultimately I can't speak for Frenqy, it's their mod now, but I wouldn't have wanted to add such a feature to my mod - I believe the feature is well-implemented in ShareSuite, and duplicating features between mods can cause compatibility issues to pop up.

Sorry for the overly long comment - in the spirit of not dragging this out or turning it into an argument, I'm gonna avoid commenting unless specifically requested. I just wanted to chime in since I have more context, but I'm a third party now, so it's not my business to try to... backseat moderate, I suppose.
